### ISSUE TITLE
swoole error

### ISSUE THREAD

**Issue by proweb** [amirfaramarzi/tower#4]
Don't get it why...
Have php 8.1 with openswoole.
But then I try to start project with `php engineer server:start` I get error:

![Снимок экрана_2022-11-03_22-11-44](https://user-images.githubusercontent.com/680073/199813124-8ef8cb21-542c-4b0c-8b1c-1b1798764dd2.png)

**Comment by amirfaramarzi** [comment]
Hi @proweb 

Unfortunately, Fomo can only be used on swoole and not on openswoole

This problem will be fixed in the next update
