### ISSUE TITLE
command not found!

### ISSUE THREAD

**Issue by bogordesaincom** [amirfaramarzi/tower#5]
error command not found!

<img width="589" alt="Jepretan Layar 2022-11-08 pukul 08 35 51" src="https://user-images.githubusercontent.com/51335197/200452426-9d8178ff-6c3c-426c-ab60-ce688bb1c428.png">

**Comment by amirfaramarzi** [comment]
It is true that there is no such command

Available and nearby commands are:

php engineer tests:run => to run all tests written by phpunit

php engineer build:test => to build a new test class
