### ISSUE TITLE
Is this abandoned or have plan to release new versions

### ISSUE THREAD

**Issue by nla-asia** [amirfaramarzi/tower#9]
Just found out this framework from benchmark website and was so impressed and excited to use for new projects. But could find a recent commit and so would like to know future plan.

**Comment by amirfaramarzi** [comment]
Hello dear nla, I am very happy to meet you

I am currently busy with other projects and haven't done anything for fomo in a few months

But my planning for this project is in such a way that with this function, more options can be added, including a dedicated interface for sql and nosql databases and databases such as elasticsearch, or the possibility of working with docker, etc.
